version: 1
disable_existing_loggers: False
formatters:
  console:
    format: "%(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console

root:
  level: INFO
  handlers: [console]
